AAOTripBooker/Controllers/DriverController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAOTripBooker.Data;
using AAOTripBooker.Models;
using AAOTripBooker.Models.ViewModels;

namespace AAOTripBooker.Controllers
{
    public class DriverController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DriverController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Driver> objList = _db.Drivers;

            foreach(var obj in objList)
            {
                obj.DriverPeriods =  _db.DriverPeriods.Where(i => i.DriverId == obj.Id).ToList();
            }

            return View(objList);

        }

        //GET-Create
        public IActionResult Create()
        {

            return View();

        }
        //POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Driver obj)
        {
            if (ModelState.IsValid)
            {
                _db.Drivers.Add(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            
            return View(obj);
        }

        //GET Delete
        public IActionResult Delete(int? id)
        {
            
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Drivers.Find(id);
            if(obj == null) { return NotFound(); }



            return View(obj);



        }

        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Drivers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }


            _db.Drivers.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");


           
        }

    }
}

AAOTripBooker/Controllers/DriverTripsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AAOTripBooker.Data;
using AAOTripBooker.Models;

namespace AAOTripBooker.Controllers
{
    public class DriverTripsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DriverTripsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DriverTrips
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DriverTrips.Include(d => d.Driver).Include(d => d.Trip);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DriverTrips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driverTrip = await _context.DriverTrips
                .Include(d => d.Driver)
                .Include(d => d.Trip)
                .FirstOrDefaultAsync(m => m.DriverId == id);
            if (driverTrip == null)
            {
                return NotFound();
            }

            return View(driverTrip);
        }

        // GET: DriverTrips/Create
        public IActionResult Create()
        {
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "DriversLicense");
            ViewData["TripId"] = new SelectList(_context.Trips, "Id", "Id");
            return View();
        }

        // POST: DriverTrips/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DriverId,TripId")] DriverTrip driverTrip)
        {
            if (ModelState.IsValid)
            {
                _context.Add(driverTrip);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "DriversLicense", driverTrip.DriverId);
            ViewData["TripId"] = new SelectList(_context.Trips, "Id", "Id", driverTrip.TripId);
            return View(driverTrip);
        }

        // GET: DriverTrips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driverTrip = await _context.DriverTrips.FindAsync(id);
            if (driverTrip == null)
            {
                return NotFound();
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "DriversLicense", driverTrip.DriverId);
            ViewData["TripId"] = new SelectList(_context.Trips, "Id", "Id", driverTrip.TripId);
            return View(driverTrip);
        }

        // POST: DriverTrips/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DriverId,TripId")] DriverTrip driverTrip)
        {
            if (id != driverTrip.DriverId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driverTrip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriverTripExists(driverTrip.DriverId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "DriversLicense", driverTrip.DriverId);
            ViewData["TripId"] = new SelectList(_context.Trips, "Id", "Id", driverTrip.TripId);
            return View(driverTrip);
        }

        // GET: DriverTrips/Delete/5
        public async Task<IActionResult> Delete(int? driverid, int? tripid)
        {
            if (driverid == null)
            {
                return NotFound();
            }

            if (tripid == null)
            {
                return NotFound();
            }

            var driverTrip = await _context.DriverTrips.Where(x => x.DriverId == driverid).Where(x => x.TripId == tripid).FirstOrDefaultAsync();
            if (driverTrip == null)
            {
                return NotFound();
            }

            return View(driverTrip);
        }

        // POST: DriverTrips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int DriverId, int TripId)
        {
            var driverTrip = await _context.DriverTrips.Where(x => x.DriverId == DriverId).Where(x => x.TripId == TripId).FirstOrDefaultAsync();
            _context.DriverTrips.Remove(driverTrip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriverTripExists(int id)
        {
            return _context.DriverTrips.Any(e => e.DriverId == id);
        }
    }
}

AAOTripBooker/Controllers/TripController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAOTripBooker.Data;
using AAOTripBooker.Models;

namespace AAOTripBooker.Controllers
{
    public class TripController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TripController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Trip> objList = _db.Trips;
            return View(objList);

        }

        //GET-Create
        public IActionResult Create()
        {
            
            return View();

        }
        //POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Trip obj)
        {
            _db.Trips.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");

        }

        //GET Delete
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Trips.Find(id);
            if (obj == null) { return NotFound(); }



            return View(obj);



        }

        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Trips.Find(id);
            if (obj == null)
            {
                return NotFound();
            }


            _db.Trips.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");



        }

        //GET Update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Trips.Find(id);
            if (obj == null) { return NotFound(); }



            return View(obj);



        }
        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Trip obj)
        {
            _db.Trips.Update(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");



        }
    }
}

AAOTripBooker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AAOTripBooker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AAOTripBooker.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AAOTripBooker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="Index">Oprettede ture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="Create">Opret tur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">Afløser oversigt</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DriverTrips" asp-action="Index">Tildelte ture</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AAOTripBooker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/92131e5917.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>